services:
  - type: web
    name: nize-logistics-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --omit=optional
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
